# Generated by Django 5.1.6 on 2025-03-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='is_donation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchandise',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
