# Generated by Django 5.1.6 on 2025-03-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0002_merchandise_is_donation_merchandise_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='is_negotiated',
            field=models.BooleanField(default=False),
        ),
    ]
