# Generated by Django 5.1.6 on 2025-03-08 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0003_merchandise_is_negotiated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise_picture',
            name='merchandise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='merchandise.merchandise'),
        ),
    ]
